# Generated by Django 3.2 on 2021-05-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210430_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('GOOGLE', 'google'), ('EMAIL', 'email')], default='GOOGLE', max_length=10),
        ),
    ]
